### ISSUE TITLE
执行 npm run dev:mp-weixin 报错

### ISSUE THREAD

**Issue by seolhw** [thiszhong/wxmp-plugin-uniapp#1]
const [mode, type] = JSON.parse(process.env.npm_config_argv).cooked[1].split(':');
这行代码报错，无法获取到 process.env.npm_config_argv ，它的值是undefind

**Comment by thiszhong** [comment]
`npm` 版本是不是 7.x，是的话，降为 6.x 试试。

**Comment by lxf-soul** [comment]
跑步起来啊

**Comment by lxf-soul** [comment]
> const [mode, type] = JSON.parse(process.env.npm_config_argv).cooked[1].split(':'); 这行代码报错，无法获取到 process.env.npm_config_argv ，它的值是undefind

请问你的跑起来了没

**Comment by lxf-soul** [comment]
这个项目怎么运行到微信开发者工具呢

**Comment by thiszhong** [comment]
@lxf-soul `npm` 版本对吗？`run` 后微信开发者工具打开项目目录即可，如果不要 `project.config.json` 则打开项目目录下的 `miniprogram`（`run` 生成的）。

**Comment by lxf-soul** [comment]
终于找到开发微信插件的东西了

**Comment by thiszhong** [comment]
#v0.0.2 已兼容最新 npm@8.x。输出目录更符合 uniapp 风格。
vue3 分支已建立，尚有问题待官方解决。
