### ISSUE TITLE
组件传参问题

### ISSUE THREAD

**Issue by JellyHell** [thiszhong/wxmp-plugin-uniapp#2]
您好,我想请教您一个问题. 我在这个项目的基础上写了一个组件. 发布之后, 可以正常接入,但是无法传参.
![image](https://user-images.githubusercontent.com/4350951/162865210-752b4494-2f7e-4b0b-a05a-aebe28eaca09.png)

![image](https://user-images.githubusercontent.com/4350951/162865276-e2b8cebd-7460-4244-b42d-92eeadf06476.png)

![image](https://user-images.githubusercontent.com/4350951/162865387-430e3d4c-031c-4442-ad3d-7eb493f1611f.png)

![image](https://user-images.githubusercontent.com/4350951/162865471-548882a5-7131-4210-89db-89c8d5fd337b.png)

![image](https://user-images.githubusercontent.com/4350951/162865601-9e3b18a8-5a05-411c-92a0-3f83c7c87337.png)

能否麻烦大神帮看下,是参数声明有问题还是接入有问题. 

我看demo里有test-sync组件,但是没有看到 原生微信小程序 怎么引用该组件的代码. 两者原理上应该是一样的.

**Comment by thiszhong** [comment]
看起来没什么毛病，我这边也有原生接入的，组件可以正常传参的。@dcloudio 的那些依赖是最新的吗？你可以拿插件的dev版本调试看看到底有没有接收到参数。

**Comment by JellyHell** [comment]
@thiszhong  直接用的你的这个项目的依赖跑的 应该是最新版本的.
新手一枚,请问下怎么用dev版调试呀

**Comment by JellyHell** [comment]
@thiszhong 直接用的你的这个项目的依赖跑的 应该是最新版本的.
在dev调试的时候 引用方是用uni写的 是可以传参的. 但正式微信小程序接入的时候 就用不了了

方便问下咱们这有原生接入的demo可参考么.

![image](https://user-images.githubusercontent.com/4350951/162890123-391f5b3c-3c5a-4447-8bd3-ada2bd258289.png)

**Comment by thiszhong** [comment]
没有demo，是项目不方便。可能可以尝试的是加个简单单词属性试试。然后我说的不是开发的 dev，是在原生的开发版小程序中测试：https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/development.html#%E5%9C%A8%E5%BC%80%E5%8F%91%E7%89%88%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%AD%E6%B5%8B%E8%AF%95

**Comment by JellyHell** [comment]
测了一下 dev环境下是可以收到参数的.  是直接在你的这个项目做的编译. 依赖应该是最新的
