### ISSUE TITLE
关于页面跳转

### ISSUE THREAD

**Issue by frealcat** [thiszhong/wxmp-plugin-uniapp#3]
![image](https://user-images.githubusercontent.com/75417018/164954100-9360bf89-51d2-4eca-a4e4-fce977411104.png)
为什么我这样写会找不到wen'jian文件呢，你那个plugin://myplugin是什么路径？

**Comment by thiszhong** [comment]
跳插件页面的话，“myPlugin”是必须的，不过字段名是可以自定义的，详见小程序接入插件：[https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/using.html#%E6%B7%BB%E5%8A%A0%E6%8F%92%E4%BB%B6](https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/using.html#%E6%B7%BB%E5%8A%A0%E6%8F%92%E4%BB%B6) 
uniapp：[https://uniapp.dcloud.io/tutorial/mp-weixin-plugin.html](https://uniapp.dcloud.io/tutorial/mp-weixin-plugin.html)
![20220424144051](https://user-images.githubusercontent.com/12380965/164960227-6fe35390-e65b-4d88-a3be-660b883b23ec.jpg)

**Comment by frealcat** [comment]
好的，谢谢
