### ISSUE TITLE
uni调微信支付

### ISSUE THREAD

**Issue by frealcat** [thiszhong/wxmp-plugin-uniapp#4]
我在调用uni.requestPayment时，会报错uni.requestPayment is not a function，debugger后发现uni上没有requestPaymen这个api，怎么回事呢？

**Comment by thiszhong** [comment]
小程序插件不支持 requestPayment，详见：https://developers.weixin.qq.com/miniprogram/dev/api/payment/wx.requestPayment.html 。
如需使用支付，可以：
1. 使用支付功能页，注意区分插件、开发插件的小程序这两个概念，详见：https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/functional-pages/request-payment.html
2. 插件使用者把小程序的 wx/uni 通过导出到插件（https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/using.html#%E5%AF%BC%E5%87%BA%E5%88%B0%E6%8F%92%E4%BB%B6 ）或插件接口传递给插件，这个上面是有requestPayment的，另外openid应该也需要传。

**Comment by frealcat** [comment]
好的，我用功能页实现了，谢谢
