### ISSUE TITLE
怎么引入scss

### ISSUE THREAD

**Issue by jiangwentao064191** [thiszhong/wxmp-plugin-uniapp#5]
怎么引入scss呢 安装node-sass运行就报错 node16 node-sass 4.x和6.x 7.x都试了

**Comment by thiszhong** [comment]
可以查看 uniapp 相关文档。

不过，由于 node-sass 诸多问题，推荐用 [dart-sass](https://www.npmjs.com/package/sass)。

**Comment by jiangwentao064191** [comment]
你好 还有个问题请教 我用真机调试就一直报错 说是严格模式下的arguments对象问题  找不出原因 开发者工具里面的代码报错 请问有什么办法可以调试真机吗   预览的时候我的appid明明是正式的 可是扫码之后就是测试号。求教
