### ISSUE TITLE
打包会生成一个 miniprogram 和 plugin 导致大小在上传时是2倍

### ISSUE THREAD

**Issue by fffandpiao** [thiszhong/wxmp-plugin-uniapp#6]
打包的内容都是一模一样的，2个文件夹，我不是很理解，我想做成页面，小于1m 倒是还行，大于1m 就*2导致无法上传了，怎么办

**Comment by thiszhong** [comment]
你是在开发微信小程序插件吗？

小程序插件本身就是3个主目录，官方文档：https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/development.html 

至于大小，取决于你的项目与设计，理论上插件和小程序不会做太多重复的东西，不存在你说的 1 * 2 的说法。然后确认你上传的时候运行的是 build 而不是 dev。

**Comment by fffandpiao** [comment]
![2022-08-31_16：01：13](https://user-images.githubusercontent.com/59195257/187625530-a2a20043-df1b-4e9e-b091-357b035c8566.png)
![image](https://user-images.githubusercontent.com/59195257/187625665-7dd7be5e-f56e-4feb-b3f2-093994a2bf74.png)
你看，我build 之后上传会把 `miniprogram` 和 `plugin` 两个文件夹的内容都算在一起，但是这两个文件夹内容都是一样的，就很无奈

**Comment by thiszhong** [comment]
你这插件本身就是这么大的吗，我觉得你可以试试：
1. 再次确认你是 build 而不是 dev；
2. 理论上 `miniprogram` （本地代码）不应该这么大，它只是调试、预览插件，一两个页面几百K足以，并且很多都应该直接加载的插件，而非在这里再开发一个系统、写很多代码，uview-ui应该都不需要用，请检查你 `miniprogram/` 下 components、pages、uview-ui，一个调试 demo 到底需不需要这么多代码。对应开发上就是：插件的代码只在 `src/plugin/` 下，调试、公共的代码放在外层 `src/` 下。
3. 有图片的话换网络地址或压缩一下；
4. 开发者工具的本地设置中的 上传时压缩打开。

**Comment by fffandpiao** [comment]
找到问题原因了 我把页面放在了 根目录下的 `pages` 中了，没理解浏览调试界面，和插件页面的区别，应该是放在 `plugin/pages` 里面才对，感谢
