### ISSUE TITLE
plugin引入vuex和宿主小程序vuex冲突

### ISSUE THREAD

**Issue by Gitby-Leo** [thiszhong/wxmp-plugin-uniapp#8]
uniapp开发的plugin和小程序都使用了vuex
```
// 插件
// #ifdef MP-WX-PLUGIN
import store from "@/store/index";
// #endif
```
本地正常，但插件打包上传成功后，在宿主小程序中引入，插件的this.$store指向了宿主小程序的vuex

请问有什么解决方案吗

**Comment by thiszhong** [comment]
本项目只是一个开发的脚手架，不包含 vuex 等业务逻辑。

你这个插件内不要把 store 注册到全局（走引入-使用）或者换个名字比如 pluginStore 试试。

**Comment by Gitby-Leo** [comment]
> 本项目只是一个开发的脚手架，不包含 vuex 等业务逻辑。
> 
> 你这个插件内不要把 store 注册到全局（走引入-使用）或者换个名字比如 pluginStore 试试。

感谢你的及时回复，由于mapState等内部使用了this.$store，换名字不太行

删掉了全局，改成了局部引入
```
//入口组件
import store from "@/store/index";
import { mapState, mapMutations } from "vuex";

beforeCreate() {
    this.$store = store;
},
```
